### ISSUE TITLE
Class 'Font_Metrics' not found

### ISSUE THREAD

**Issue by elimentz** [PhenX/php-font-lib#22]
Hi

I'm using dompdf to generate PDFs in my Laravel application. I'm trying to convert a font to so I can use it in a pdf, but there are some issues with it. Initially, I received the "Class 'Font' not found" error, which I was able to solve by downloading the repository and copying it to the right location as marked [here](http://stackoverflow.com/questions/13431905/php-font-lib-must-either-be-installed-via-composer-or-copied-to-lib-php-font-lib) on StackOverflow. This solved my issue, but in turn generated a new one: "Class 'Font_Metrics' not found", which I have not been able to solve. 

Additional info: 
- dompdf was installed via composer and works correctly - PDF generation is fully functional
- The command I use is the following: 
```php
vendor/dompdf/dompdf/load_font.php Arial /fonts/Arial.ttf /fonts/Arial-Bold.ttf /fonts/Arial-Italic.ttf /fonts/Arial-Bold-Italic.ttf
```

Stack trace:
```php
PHP Fatal error:  Class 'Font_Metrics' not found in vendor/dompdf/dompdf/load_font.php on line 67
PHP Stack trace:
PHP   1. {main}() vendor/dompdf/dompdf/load_font.php:0
PHP   2. call_user_func_array:{vendor/dompdf/dompdf/load_font.php:171}() vendor/dompdf/dompdf/load_font.php:171
PHP   3. install_font_family() vendor/dompdf/dompdf/load_font.php:171
```

Any help is appreciated

**Comment by bsweeney** [comment]
When using dompdf make sure you are using the correct version of php-font-lib. With dompdf 0.6.1 you should be using [php-font-lib 0.2.2](https://github.com/PhenX/php-font-lib/releases/tag/0.2.2).

**Comment by elimentz** [comment]
Thx for the quick assist, issue resolved
