### ISSUE TITLE
dompdf/lib/php-font-lib/classes/Font.php

### ISSUE THREAD

**Issue by AlNahari** [PhenX/php-font-lib#24]
Where is this tree of files?

**Comment by bsweeney** [comment]
You have to download [v2.2 of php-font-lib](https://github.com/PhenX/php-font-lib/releases/tag/0.2.2).

However, if you're having trouble getting all the files to use with dompdf we recommended you download the archived version of the latest release ([currently v0.6.1](https://github.com/dompdf/dompdf/releases/download/v0.6.1/dompdf-0.6.1.zip)), which includes all the files you need.
