### ISSUE TITLE
Undefined index: OS/2

### ISSUE THREAD

**Issue by fitoe** [PhenX/php-font-lib#33]
when I call getTableObject("OS/2")->data["ANY_COLUM"] , it will cause this error.
ps: Very thanks for your great works!

**Comment by fitoe** [comment]
I use this:
` $font->getData("OS/2","panose")[3]`
done.

**Comment by oxygens** [comment]
Did u call ::parse() first?

**Comment by PhenX** [comment]
@fitoe can you tell us which font did you use to have this issue please ?

**Comment by fitoe** [comment]
oxygens :+1: Thanks, it works.
