### ISSUE TITLE
Doesn't work for this ttf file:name error, unicode map empty

### ISSUE THREAD

**Issue by fitoe** [PhenX/php-font-lib#45]
But I can't upload this file of 文鼎CS大黑繁.ttf
could I have your e-mail address? And I will send you the attachment.

**Comment by PhenX** [comment]
Is this font downloadable somewhere on the web ?

**Comment by fitoe** [comment]
[download](http://down.zhaozi.cn/gfonts/wending/%E6%96%87%E9%BC%8ECS%E5%A4%A7%E9%BB%91%E7%B9%81.ttf
)

Thanks.

**Comment by PhenX** [comment]
Ok, this is the same problem as in #40, I'll try to take a look at this, but if anyone is able to make a pull request, he's welcome :)
