### ISSUE TITLE
Undefined offset

### ISSUE THREAD

**Issue by tostercx** [PhenX/php-font-lib#50]
Hi,

I sometimes get undefined offsets at this line:
https://github.com/PhenX/php-font-lib/blob/0.4/src/FontLib/BinaryStream.php#L379

Happened when using Dompdf with font stripping turned on with bold Times New Roman.
It seems to work correctly if I check if `$data[$i]` is set and return `null` otherwise.

```
$ret += $this->w($type[0], isset($data[$i]) ? $data[$i] : null);
```
##

**Comment by PhenX** [comment]
Fixed by 010c3e0e22a9ab0d9f93678692c80865f041e2d2
