### ISSUE TITLE
unpack(): Type n: not enough input, need 2, have 0

### ISSUE THREAD

**Issue by samhibberd** [PhenX/php-font-lib#51]
Hi There,

We are running into issues with our custom fonts (which strangely have been working before) when both installing automatically and using the dompdf  load_fonts.php utility by @bsweeney

It looks like the error we hit is in php-font-lib, here is the console output:

> Sams-iMac:dompdf samhibberd$ php load_font.php NMSyms /Users/samhibberd/Desktop/NMSyms.ttf
> 
> Unable to find bold face file.
> Unable to find italic face file.
> Unable to find bold_italic face file.
> Copying /Users/samhibberd/Desktop/NMSyms.ttf to /Users/samhibberd/Sites/vasco-web/craft/plugins/vasco/vendor/dompdf/dompdf/lib/fonts/NMSyms.ttf...
> Generating Adobe Font Metrics for /Users/samhibberd/Sites/vasco-web/craft/plugins/vasco/vendor/dompdf/dompdf/lib/fonts/NMSyms...
> 
> Warning: unpack(): Type n: not enough input, need 2, have 0 in /Users/samhibberd/Sites/vasco-web/craft/plugins/vasco/vendor/phenx/php-font-lib/src/FontLib/BinaryStream.php on line 183
> 
> Warning: unpack(): Type n: not enough input, need 2, have 0 in /Users/samhibberd/Sites/vasco-web/craft/plugins/vasco/vendor/phenx/php-font-lib/src/FontLib/BinaryStream.php on line 183

NB. I have removed some date() and strftime() warnings as they appear to have fallback values.

Any ideas??

Thanks.
## 

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/36195727-unpack-type-n-not-enough-input-need-2-have-0?utm_campaign=plugin&utm_content=tracker%2F317728&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F317728&utm_medium=issues&utm_source=github).

**Comment by bsweeney** [comment]
(also see #47)

**Comment by bsweeney** [comment]
closing, please subscribe to 47 for updates

**Comment by lucianoo6** [comment]
infelizmente esse erro e devido a um falta de caractere porem eu uso o @ pra suprimir o erro pois ainda não encontrei outra solução exemplo: 

    `$answerHeader    = @unpack('ntype/nclass/Nttl/nlength', $answerHeaderBin);`
