### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by mnabialek** [PhenX/php-font-lib#53]
Can you create new 0.4.1 release? There are some issues in current release that were resolved but not released yet.

**Comment by tuscanicz** [comment]
+1
we really need some fixes, such as issue #43 and update dependencies of Dompdf library.

**Comment by milanmimra** [comment]
:+1:

**Comment by oytuntez** [comment]
Also #52. We were just about to fork our own copy, but we'd much prefer to wait for this repo to be updated.

**Comment by PhenX** [comment]
Done :) https://github.com/PhenX/php-font-lib/releases/tag/0.5
