### ISSUE TITLE
A glyph with more than one unicode

### ISSUE THREAD

**Issue by danyamasadeh** [PhenX/php-font-lib#56]
I am working on an arabic font, and in PS I can see some glyphs have more one unicode separated by comma, these chars appear as squares. and the generated unicode for these chars  in this lib is wrong. how I can get the correct unicode for these glyphs?

**Comment by PhenX** [comment]
Did you find a solution, or is the problem still present ?

**Comment by danyamasadeh** [comment]
I found a solution, many thanks to get back to me
