### ISSUE TITLE
Exception on PHP 7.4: Trying to access array offset on value of type null

### ISSUE THREAD

**Issue by dtvmedia** [PhenX/php-font-lib#75]
Hi, I just tried a project of mine on PHP 7.4 and I experienced the following exception there related to this lib when rendering a pdf with dompdf: 

ErrorException: Trying to access array offset on value of type null in AdobeFontMetrics.php line 142

**Comment by bsweeney** [comment]
Will try to get a release out soon-ish to address PHP compatibility issues.

**Comment by dvdmarchetti** [comment]
This fix also solved me the PDF generation when I render an HTML template that uses a Google Fonts stylesheet without the needs to download any ttf font on the server.

**Comment by dtvmedia** [comment]
Any plans when this will be released? Thats the only package holding me back from upgrading to PHP 7.4.

**Comment by marijnbent** [comment]
@bsweeney Why not releasing this in the meantime? This fix would solve the error most people have.

**Comment by cicoasm** [comment]
It doesn't work with php 7.4, from many problems.

**Comment by bsweeney** [comment]
Just want to note that PhenX released 0.5.2 April 12.
