### ISSUE TITLE
Does this package support with php 7.0 version?

### ISSUE THREAD

**Issue by kashifmit** [PhenX/php-font-lib#80]
Hi, 
I am using php 7.0 version, and i am getting errors in it, can you please let me know how can i use it for php 7.0?

**Comment by enumag** [comment]
At least specify that errors do you see.

**Comment by kashifmit** [comment]
@enumag 
Thanks for your reply
I am using this package in laravel 5.2 with php 7.0 version. It is working fine on my local xamp server using windows platform. But when i deployed it on server which is in ubuntu it gives me error message ```ErrorException: iconv(): Detected an incomplete multibyte character in input string in /var/www/html/vendor/symfony/polyfill-mbstring/Mbstring.php:115``` And also give the parse function error on my controller line. Can you please let me know what i am missing?

**Comment by bsweeney** [comment]
That error does not appear to be coming from this library.

If you're sure it is it would help to see a sample of your usage.
