### ISSUE TITLE
Good afternoon.  Can I get acquainted with the source codes of gui demo, as an example of working with the php-font-lib library?

### ISSUE THREAD

**Issue by Biomehanik** [PhenX/php-font-lib#82]
Good afternoon.  Can I get acquainted with the source codes of gui demo, as an example of working with the php-font-lib library?

**Comment by PhenX** [comment]
Hello, here it is
[php-font-lib-demo.zip](https://github.com/PhenX/php-font-lib/files/4570953/php-font-lib-demo.zip)
